name: Run Tests in Docker

on:
  push:
    branches:
      - main

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-test-app .

      - name: Run tests inside Docker container
        run: docker run my-test-app
